# Generated by Django 5.0.4 on 2025-11-13 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField()),
                ('position', models.CharField(choices=[('Guard', 'Guard'), ('Forward', 'Forward'), ('Center', 'Center'), ('Guard / Forward', 'Guard / Forward'), ('Forward / Center', 'Forward / Center')], max_length=20)),
                ('games', models.IntegerField(blank=True, null=True)),
                ('minutes_per_game', models.FloatField(blank=True, null=True)),
                ('points_per_game', models.FloatField(blank=True, null=True)),
                ('rebounds_per_game', models.FloatField(blank=True, null=True)),
                ('assists_per_game', models.FloatField(blank=True, null=True)),
                ('steals_per_game', models.FloatField(blank=True, null=True)),
                ('blocks_per_game', models.FloatField(blank=True, null=True)),
                ('fouls_per_game', models.FloatField(blank=True, null=True)),
                ('turnovers_per_game', models.FloatField(blank=True, null=True)),
                ('two_points_pct', models.FloatField(blank=True, null=True)),
                ('three_points_pct', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.team')),
            ],
        ),
    ]
